---
name: Chrome - National Geographic
author: Gladysfotsa <gladysfotsa99@gmail.com>
description: Benchmarking Chrome loading National Geographic for 5 minutes

architecture: Linux

services:
  chrome-container:
    image: gladysfotsa/chrome_energy_image
    environment:
      URL_TO_VISIT: "https://www.nationalgeographic.com"
    command: /usr/local/bin/chrome-entry.sh

flow:
  - name: Load National Geographic in Chrome
    container: chrome-container
    commands:
      - type: console
        command: echo "Opening National Geographic..."
      - type: console
        command: sleep 300
        note: Wait for Chrome to run and render the page for 5 minutes
